import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>naive art</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex h-screen justify-center items-center">
        <div className="">wow</div>
      </div>
    </>
  )
}

export default Home
