import type { NextPage } from 'next'
import Head from 'next/head'
import { ApolloClient, InMemoryCache, gql } from '@apollo/client';

const Home: NextPage = () => {

  async function handleClick() {
    const client = new ApolloClient({
      uri: "http://localhost:5001/graphql",
      cache: new InMemoryCache(),
    });
  
    client
      .query({
        query: gql`
      query GetArtists {
        allArtists {
         name,
         id,
         dateOfBirth
         }
       }
      `,
      })
      .then((result) => console.log(result))
  }

  return (
    <>
      <Head>
        <title>naive art</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="flex flex-col h-screen justify-center items-center">
        <button onClick={handleClick} className='p-2 border-2 border-black'>fetch</button>
      </div>
    </>
  )
}

export default Home
